<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdIjKzL\InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdIjKzL/InfrastructureApp_Infrastructure_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEdIjKzL.legacy');

    return;
}

if (!\class_exists(InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEdIjKzL\InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false);
}

return new \ContainerEdIjKzL\InfrastructureApp_Infrastructure_KernelDevDebugContainer(array(
    'container.build_hash' => 'EdIjKzL',
    'container.build_id' => '69f0dbb0',
    'container.build_time' => 1546604339,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdIjKzL');
