<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxmL1xb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerWxmL1xb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxmL1xb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxmL1xb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWxmL1xb\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'WxmL1xb',
    'container.build_id' => 'f3c8fa93',
    'container.build_time' => 1546599385,
), __DIR__ . \DIRECTORY_SEPARATOR);
