version: "3"

services:

  blog-nginx:
    container_name: "blog-nginx"
    image: "nginx"
    build:
      context: "./nginx"
    ports:
      - "${NGINX_LISTEN_PORT}:80"
    volumes:
      - "./nginx/configs/bohdanblog.loc.conf:/etc/nginx/conf.d/bohdanblog.loc.conf"
      - "./nginx/logs:/var/log/nginx"
      - "../:/bohdanblog.loc"
    depends_on:
      - "blog-php-fpm"

  blog-php-fpm:
    container_name: "blog-php-fpm"
    image: "php_fpm"
    build:
      context: "./php-fpm"
    volumes:
      - "../:/bohdanblog.loc"
    depends_on:
      - "blog-mysql"

  blog-mysql:
    container_name: "blog-mysql"
    image: "mysql"
    build:
      context: "./mysql"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "blog-mysql-volume:/var/lib/mysql"
    ports:
      - "${MYSQL_LISTEN_PORT}:3306"

volumes:
  blog-mysql-volume: