version: "3"

services:

  nginx:
    image: "nginx"
    build:
      context: "./nginx"
    ports:
      - "80:80"
    volumes:
      - "./nginx/configs/bohdanblog.loc.conf:/etc/nginx/conf.d/bohdanblog.loc.conf"
      - "./nginx/logs:/var/log/nginx"
      - "../:/bohdanblog.loc"
    depends_on:
      - "php-fpm"
  php-fpm:
    image: "php_fpm"
    build:
      context: "./php-fpm"
    volumes:
      - "../:/bohdanblog.loc"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql"
    build:
      context: "./mysql"
    environment:
      MYSQL_DATABASE: "bohdanblog"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    volumes:
      - "mysql-volume:/var/lib/mysql"
    ports:
      - "3307:3306"

volumes:
  mysql-volume: