parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            UserId: Infrastructure\Types\DoctrineUserId
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            Domain\User\User:
                type: yml
                is_bundle: false
                prefix: Domain\User\User
                dir: '%kernel.project_dir%/src/Mapping/User/User'
            Domain\User\Admin:
                type: yml
                is_bundle: false
                prefix: Domain\User\Admin
                dir: '%kernel.project_dir%/src/Mapping/User/Admin'